%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

if isoctave || matlab_ver_less_than('8.6')
    clear all
else
    clearvars -global
    clear_persistent_variables(fileparts(which('dynare')), false)
end
tic0 = tic;
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'SW';
M_.dynare_version = '5.4';
oo_.dynare_version = '5.4';
options_.dynare_version = '5.4';
%
% Some global variables initialization
%
global_initialization;
M_.exo_names = cell(7,1);
M_.exo_names_tex = cell(7,1);
M_.exo_names_long = cell(7,1);
M_.exo_names(1) = {'ea'};
M_.exo_names_tex(1) = {'ea'};
M_.exo_names_long(1) = {'ea'};
M_.exo_names(2) = {'eb'};
M_.exo_names_tex(2) = {'eb'};
M_.exo_names_long(2) = {'eb'};
M_.exo_names(3) = {'eg'};
M_.exo_names_tex(3) = {'eg'};
M_.exo_names_long(3) = {'eg'};
M_.exo_names(4) = {'eqs'};
M_.exo_names_tex(4) = {'eqs'};
M_.exo_names_long(4) = {'eqs'};
M_.exo_names(5) = {'em'};
M_.exo_names_tex(5) = {'em'};
M_.exo_names_long(5) = {'em'};
M_.exo_names(6) = {'epinf'};
M_.exo_names_tex(6) = {'epinf'};
M_.exo_names_long(6) = {'epinf'};
M_.exo_names(7) = {'ew'};
M_.exo_names_tex(7) = {'ew'};
M_.exo_names_long(7) = {'ew'};
M_.endo_names = cell(41,1);
M_.endo_names_tex = cell(41,1);
M_.endo_names_long = cell(41,1);
M_.endo_names(1) = {'labobs'};
M_.endo_names_tex(1) = {'labobs'};
M_.endo_names_long(1) = {'labobs'};
M_.endo_names(2) = {'robs'};
M_.endo_names_tex(2) = {'robs'};
M_.endo_names_long(2) = {'robs'};
M_.endo_names(3) = {'pinfobs'};
M_.endo_names_tex(3) = {'pinfobs'};
M_.endo_names_long(3) = {'pinfobs'};
M_.endo_names(4) = {'dy'};
M_.endo_names_tex(4) = {'dy'};
M_.endo_names_long(4) = {'dy'};
M_.endo_names(5) = {'dc'};
M_.endo_names_tex(5) = {'dc'};
M_.endo_names_long(5) = {'dc'};
M_.endo_names(6) = {'dinve'};
M_.endo_names_tex(6) = {'dinve'};
M_.endo_names_long(6) = {'dinve'};
M_.endo_names(7) = {'dw'};
M_.endo_names_tex(7) = {'dw'};
M_.endo_names_long(7) = {'dw'};
M_.endo_names(8) = {'ewma'};
M_.endo_names_tex(8) = {'ewma'};
M_.endo_names_long(8) = {'ewma'};
M_.endo_names(9) = {'epinfma'};
M_.endo_names_tex(9) = {'epinfma'};
M_.endo_names_long(9) = {'epinfma'};
M_.endo_names(10) = {'zcapf'};
M_.endo_names_tex(10) = {'zcapf'};
M_.endo_names_long(10) = {'zcapf'};
M_.endo_names(11) = {'rkf'};
M_.endo_names_tex(11) = {'rkf'};
M_.endo_names_long(11) = {'rkf'};
M_.endo_names(12) = {'kf'};
M_.endo_names_tex(12) = {'kf'};
M_.endo_names_long(12) = {'kf'};
M_.endo_names(13) = {'pkf'};
M_.endo_names_tex(13) = {'pkf'};
M_.endo_names_long(13) = {'pkf'};
M_.endo_names(14) = {'cf'};
M_.endo_names_tex(14) = {'cf'};
M_.endo_names_long(14) = {'cf'};
M_.endo_names(15) = {'invef'};
M_.endo_names_tex(15) = {'invef'};
M_.endo_names_long(15) = {'invef'};
M_.endo_names(16) = {'yf'};
M_.endo_names_tex(16) = {'yf'};
M_.endo_names_long(16) = {'yf'};
M_.endo_names(17) = {'labf'};
M_.endo_names_tex(17) = {'labf'};
M_.endo_names_long(17) = {'labf'};
M_.endo_names(18) = {'wf'};
M_.endo_names_tex(18) = {'wf'};
M_.endo_names_long(18) = {'wf'};
M_.endo_names(19) = {'rrf'};
M_.endo_names_tex(19) = {'rrf'};
M_.endo_names_long(19) = {'rrf'};
M_.endo_names(20) = {'mc'};
M_.endo_names_tex(20) = {'mc'};
M_.endo_names_long(20) = {'mc'};
M_.endo_names(21) = {'zcap'};
M_.endo_names_tex(21) = {'zcap'};
M_.endo_names_long(21) = {'zcap'};
M_.endo_names(22) = {'rk'};
M_.endo_names_tex(22) = {'rk'};
M_.endo_names_long(22) = {'rk'};
M_.endo_names(23) = {'k'};
M_.endo_names_tex(23) = {'k'};
M_.endo_names_long(23) = {'k'};
M_.endo_names(24) = {'pk'};
M_.endo_names_tex(24) = {'pk'};
M_.endo_names_long(24) = {'pk'};
M_.endo_names(25) = {'c'};
M_.endo_names_tex(25) = {'c'};
M_.endo_names_long(25) = {'c'};
M_.endo_names(26) = {'inve'};
M_.endo_names_tex(26) = {'inve'};
M_.endo_names_long(26) = {'inve'};
M_.endo_names(27) = {'y'};
M_.endo_names_tex(27) = {'y'};
M_.endo_names_long(27) = {'y'};
M_.endo_names(28) = {'lab'};
M_.endo_names_tex(28) = {'lab'};
M_.endo_names_long(28) = {'lab'};
M_.endo_names(29) = {'pinf'};
M_.endo_names_tex(29) = {'pinf'};
M_.endo_names_long(29) = {'pinf'};
M_.endo_names(30) = {'w'};
M_.endo_names_tex(30) = {'w'};
M_.endo_names_long(30) = {'w'};
M_.endo_names(31) = {'r'};
M_.endo_names_tex(31) = {'r'};
M_.endo_names_long(31) = {'r'};
M_.endo_names(32) = {'a'};
M_.endo_names_tex(32) = {'a'};
M_.endo_names_long(32) = {'a'};
M_.endo_names(33) = {'b'};
M_.endo_names_tex(33) = {'b'};
M_.endo_names_long(33) = {'b'};
M_.endo_names(34) = {'g'};
M_.endo_names_tex(34) = {'g'};
M_.endo_names_long(34) = {'g'};
M_.endo_names(35) = {'qs'};
M_.endo_names_tex(35) = {'qs'};
M_.endo_names_long(35) = {'qs'};
M_.endo_names(36) = {'ms'};
M_.endo_names_tex(36) = {'ms'};
M_.endo_names_long(36) = {'ms'};
M_.endo_names(37) = {'spinf'};
M_.endo_names_tex(37) = {'spinf'};
M_.endo_names_long(37) = {'spinf'};
M_.endo_names(38) = {'sw'};
M_.endo_names_tex(38) = {'sw'};
M_.endo_names_long(38) = {'sw'};
M_.endo_names(39) = {'kpf'};
M_.endo_names_tex(39) = {'kpf'};
M_.endo_names_long(39) = {'kpf'};
M_.endo_names(40) = {'kp'};
M_.endo_names_tex(40) = {'kp'};
M_.endo_names_long(40) = {'kp'};
M_.endo_names(41) = {'Exp_pinf'};
M_.endo_names_tex(41) = {'Exp\_pinf'};
M_.endo_names_long(41) = {'Exp_pinf'};
M_.endo_partitions = struct();
M_.param_names = cell(44,1);
M_.param_names_tex = cell(44,1);
M_.param_names_long = cell(44,1);
M_.param_names(1) = {'curvw'};
M_.param_names_tex(1) = {'curvw'};
M_.param_names_long(1) = {'curvw'};
M_.param_names(2) = {'cgy'};
M_.param_names_tex(2) = {'cgy'};
M_.param_names_long(2) = {'cgy'};
M_.param_names(3) = {'curvp'};
M_.param_names_tex(3) = {'curvp'};
M_.param_names_long(3) = {'curvp'};
M_.param_names(4) = {'constelab'};
M_.param_names_tex(4) = {'constelab'};
M_.param_names_long(4) = {'constelab'};
M_.param_names(5) = {'constepinf'};
M_.param_names_tex(5) = {'constepinf'};
M_.param_names_long(5) = {'constepinf'};
M_.param_names(6) = {'constebeta'};
M_.param_names_tex(6) = {'constebeta'};
M_.param_names_long(6) = {'constebeta'};
M_.param_names(7) = {'cmaw'};
M_.param_names_tex(7) = {'cmaw'};
M_.param_names_long(7) = {'cmaw'};
M_.param_names(8) = {'cmap'};
M_.param_names_tex(8) = {'cmap'};
M_.param_names_long(8) = {'cmap'};
M_.param_names(9) = {'calfa'};
M_.param_names_tex(9) = {'calfa'};
M_.param_names_long(9) = {'calfa'};
M_.param_names(10) = {'czcap'};
M_.param_names_tex(10) = {'czcap'};
M_.param_names_long(10) = {'czcap'};
M_.param_names(11) = {'csadjcost'};
M_.param_names_tex(11) = {'csadjcost'};
M_.param_names_long(11) = {'csadjcost'};
M_.param_names(12) = {'ctou'};
M_.param_names_tex(12) = {'ctou'};
M_.param_names_long(12) = {'ctou'};
M_.param_names(13) = {'csigma'};
M_.param_names_tex(13) = {'csigma'};
M_.param_names_long(13) = {'csigma'};
M_.param_names(14) = {'chabb'};
M_.param_names_tex(14) = {'chabb'};
M_.param_names_long(14) = {'chabb'};
M_.param_names(15) = {'ccs'};
M_.param_names_tex(15) = {'ccs'};
M_.param_names_long(15) = {'ccs'};
M_.param_names(16) = {'cinvs'};
M_.param_names_tex(16) = {'cinvs'};
M_.param_names_long(16) = {'cinvs'};
M_.param_names(17) = {'cfc'};
M_.param_names_tex(17) = {'cfc'};
M_.param_names_long(17) = {'cfc'};
M_.param_names(18) = {'cindw'};
M_.param_names_tex(18) = {'cindw'};
M_.param_names_long(18) = {'cindw'};
M_.param_names(19) = {'cprobw'};
M_.param_names_tex(19) = {'cprobw'};
M_.param_names_long(19) = {'cprobw'};
M_.param_names(20) = {'cindp'};
M_.param_names_tex(20) = {'cindp'};
M_.param_names_long(20) = {'cindp'};
M_.param_names(21) = {'cprobp'};
M_.param_names_tex(21) = {'cprobp'};
M_.param_names_long(21) = {'cprobp'};
M_.param_names(22) = {'csigl'};
M_.param_names_tex(22) = {'csigl'};
M_.param_names_long(22) = {'csigl'};
M_.param_names(23) = {'clandaw'};
M_.param_names_tex(23) = {'clandaw'};
M_.param_names_long(23) = {'clandaw'};
M_.param_names(24) = {'crdpi'};
M_.param_names_tex(24) = {'crdpi'};
M_.param_names_long(24) = {'crdpi'};
M_.param_names(25) = {'crpi'};
M_.param_names_tex(25) = {'crpi'};
M_.param_names_long(25) = {'crpi'};
M_.param_names(26) = {'crdy'};
M_.param_names_tex(26) = {'crdy'};
M_.param_names_long(26) = {'crdy'};
M_.param_names(27) = {'cry'};
M_.param_names_tex(27) = {'cry'};
M_.param_names_long(27) = {'cry'};
M_.param_names(28) = {'crr'};
M_.param_names_tex(28) = {'crr'};
M_.param_names_long(28) = {'crr'};
M_.param_names(29) = {'crhoa'};
M_.param_names_tex(29) = {'crhoa'};
M_.param_names_long(29) = {'crhoa'};
M_.param_names(30) = {'crhoas'};
M_.param_names_tex(30) = {'crhoas'};
M_.param_names_long(30) = {'crhoas'};
M_.param_names(31) = {'crhob'};
M_.param_names_tex(31) = {'crhob'};
M_.param_names_long(31) = {'crhob'};
M_.param_names(32) = {'crhog'};
M_.param_names_tex(32) = {'crhog'};
M_.param_names_long(32) = {'crhog'};
M_.param_names(33) = {'crhols'};
M_.param_names_tex(33) = {'crhols'};
M_.param_names_long(33) = {'crhols'};
M_.param_names(34) = {'crhoqs'};
M_.param_names_tex(34) = {'crhoqs'};
M_.param_names_long(34) = {'crhoqs'};
M_.param_names(35) = {'crhoms'};
M_.param_names_tex(35) = {'crhoms'};
M_.param_names_long(35) = {'crhoms'};
M_.param_names(36) = {'crhopinf'};
M_.param_names_tex(36) = {'crhopinf'};
M_.param_names_long(36) = {'crhopinf'};
M_.param_names(37) = {'crhow'};
M_.param_names_tex(37) = {'crhow'};
M_.param_names_long(37) = {'crhow'};
M_.param_names(38) = {'ctrend'};
M_.param_names_tex(38) = {'ctrend'};
M_.param_names_long(38) = {'ctrend'};
M_.param_names(39) = {'cg'};
M_.param_names_tex(39) = {'cg'};
M_.param_names_long(39) = {'cg'};
M_.param_names(40) = {'alpha_int'};
M_.param_names_tex(40) = {'alpha\_int'};
M_.param_names_long(40) = {'alpha_int'};
M_.param_names(41) = {'rho_alpha'};
M_.param_names_tex(41) = {'rho\_alpha'};
M_.param_names_long(41) = {'rho_alpha'};
M_.param_names(42) = {'rho'};
M_.param_names_tex(42) = {'rho'};
M_.param_names_long(42) = {'rho'};
M_.param_names(43) = {'lam'};
M_.param_names_tex(43) = {'lam'};
M_.param_names_long(43) = {'lam'};
M_.param_names(44) = {'alpha'};
M_.param_names_tex(44) = {'alpha'};
M_.param_names_long(44) = {'alpha'};
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 7;
M_.endo_nbr = 41;
M_.param_nbr = 44;
M_.orig_endo_nbr = 41;
M_.aux_vars = [];
options_.varobs = cell(7, 1);
options_.varobs(1)  = {'dy'};
options_.varobs(2)  = {'dc'};
options_.varobs(3)  = {'dinve'};
options_.varobs(4)  = {'labobs'};
options_.varobs(5)  = {'pinfobs'};
options_.varobs(6)  = {'dw'};
options_.varobs(7)  = {'robs'};
options_.varobs_id = [ 4 5 6 1 3 7 2  ];
M_ = setup_solvers(M_);
M_.Sigma_e = zeros(7, 7);
M_.Correlation_matrix = eye(7, 7);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = true;
M_.det_shocks = [];
M_.surprise_shocks = [];
M_.heteroskedastic_shocks.Qvalue_orig = [];
M_.heteroskedastic_shocks.Qscale_orig = [];
options_.linear = true;
options_.block = false;
options_.bytecode = false;
options_.use_dll = false;
M_.nonzero_hessian_eqs = [];
M_.hessian_eq_zero = isempty(M_.nonzero_hessian_eqs);
M_.orig_eq_nbr = 41;
M_.eq_nbr = 41;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./+' M_.fname '/set_auxiliary_variables.m'], 'file') == 2;
M_.epilogue_names = {};
M_.epilogue_var_list_ = {};
M_.orig_maximum_endo_lag = 1;
M_.orig_maximum_endo_lead = 1;
M_.orig_maximum_exo_lag = 0;
M_.orig_maximum_exo_lead = 0;
M_.orig_maximum_exo_det_lag = 0;
M_.orig_maximum_exo_det_lead = 0;
M_.orig_maximum_lag = 1;
M_.orig_maximum_lead = 1;
M_.orig_maximum_lag_with_diffs_expanded = 1;
M_.lead_lag_incidence = [
 0 21 0;
 0 22 0;
 0 23 0;
 0 24 0;
 0 25 0;
 0 26 0;
 0 27 0;
 1 28 0;
 2 29 0;
 0 30 0;
 0 31 62;
 0 32 0;
 0 33 63;
 3 34 64;
 4 35 65;
 5 36 0;
 0 37 66;
 0 38 0;
 0 39 0;
 0 40 0;
 0 41 0;
 0 42 67;
 0 43 0;
 0 44 68;
 6 45 69;
 7 46 70;
 8 47 0;
 0 48 71;
 9 49 72;
 10 50 73;
 11 51 0;
 12 52 0;
 13 53 0;
 14 54 0;
 15 55 0;
 16 56 0;
 17 57 0;
 18 58 0;
 19 59 0;
 20 60 0;
 0 61 0;]';
M_.nstatic = 15;
M_.nfwrd   = 6;
M_.npred   = 14;
M_.nboth   = 6;
M_.nsfwrd   = 12;
M_.nspred   = 20;
M_.ndynamic   = 26;
M_.dynamic_tmp_nbr = [19; 0; 0; 0; ];
M_.model_local_variables_dynamic_tt_idxs = {
};
M_.equations_tags = {
  1 , 'name' , 'Exp_pinf' ;
  2 , 'name' , 'a' ;
  3 , 'name' , 'zcapf' ;
  4 , 'name' , 'rkf' ;
  5 , 'name' , 'kf' ;
  6 , 'name' , 'invef' ;
  7 , 'name' , 'pkf' ;
  8 , 'name' , 'cf' ;
  9 , 'name' , 'yf' ;
  10 , 'name' , '10' ;
  11 , 'name' , 'wf' ;
  12 , 'name' , 'kpf' ;
  13 , 'name' , 'mc' ;
  14 , 'name' , 'zcap' ;
  15 , 'name' , 'rk' ;
  16 , 'name' , 'k' ;
  17 , 'name' , 'inve' ;
  18 , 'name' , 'pk' ;
  19 , 'name' , 'c' ;
  20 , 'name' , 'y' ;
  21 , 'name' , '21' ;
  22 , 'name' , 'pinf' ;
  23 , 'name' , 'w' ;
  24 , 'name' , 'r' ;
  25 , 'name' , '25' ;
  26 , 'name' , 'b' ;
  27 , 'name' , 'g' ;
  28 , 'name' , 'qs' ;
  29 , 'name' , 'ms' ;
  30 , 'name' , 'spinf' ;
  31 , 'name' , 'epinfma' ;
  32 , 'name' , 'sw' ;
  33 , 'name' , 'ewma' ;
  34 , 'name' , 'kp' ;
  35 , 'name' , 'dy' ;
  36 , 'name' , 'dc' ;
  37 , 'name' , 'dinve' ;
  38 , 'name' , 'dw' ;
  39 , 'name' , 'pinfobs' ;
  40 , 'name' , 'robs' ;
  41 , 'name' , 'labobs' ;
};
M_.mapping.labobs.eqidx = [41 ];
M_.mapping.robs.eqidx = [40 ];
M_.mapping.pinfobs.eqidx = [39 ];
M_.mapping.dy.eqidx = [35 ];
M_.mapping.dc.eqidx = [36 ];
M_.mapping.dinve.eqidx = [37 ];
M_.mapping.dw.eqidx = [38 ];
M_.mapping.ewma.eqidx = [32 33 ];
M_.mapping.epinfma.eqidx = [30 31 ];
M_.mapping.zcapf.eqidx = [3 5 9 ];
M_.mapping.rkf.eqidx = [2 3 4 7 ];
M_.mapping.kf.eqidx = [4 5 10 ];
M_.mapping.pkf.eqidx = [6 7 ];
M_.mapping.cf.eqidx = [8 9 11 ];
M_.mapping.invef.eqidx = [6 9 12 ];
M_.mapping.yf.eqidx = [9 10 24 ];
M_.mapping.labf.eqidx = [4 8 10 11 ];
M_.mapping.wf.eqidx = [2 4 11 ];
M_.mapping.rrf.eqidx = [7 8 ];
M_.mapping.mc.eqidx = [13 22 ];
M_.mapping.zcap.eqidx = [14 16 20 ];
M_.mapping.rk.eqidx = [13 14 15 18 ];
M_.mapping.k.eqidx = [15 16 21 ];
M_.mapping.pk.eqidx = [17 18 ];
M_.mapping.c.eqidx = [19 20 23 36 ];
M_.mapping.inve.eqidx = [17 20 34 37 ];
M_.mapping.y.eqidx = [20 21 24 35 ];
M_.mapping.lab.eqidx = [15 19 21 23 41 ];
M_.mapping.pinf.eqidx = [18 19 22 23 24 39 ];
M_.mapping.w.eqidx = [13 15 23 38 ];
M_.mapping.r.eqidx = [18 19 24 40 ];
M_.mapping.a.eqidx = [2 10 13 21 25 ];
M_.mapping.b.eqidx = [7 8 18 19 26 ];
M_.mapping.g.eqidx = [9 20 27 ];
M_.mapping.qs.eqidx = [6 12 17 28 34 ];
M_.mapping.ms.eqidx = [24 29 ];
M_.mapping.spinf.eqidx = [22 30 ];
M_.mapping.sw.eqidx = [23 32 ];
M_.mapping.kpf.eqidx = [5 12 ];
M_.mapping.kp.eqidx = [16 34 ];
M_.mapping.Exp_pinf.eqidx = [1 ];
M_.mapping.ea.eqidx = [25 27 ];
M_.mapping.eb.eqidx = [26 ];
M_.mapping.eg.eqidx = [27 ];
M_.mapping.eqs.eqidx = [28 ];
M_.mapping.em.eqidx = [29 ];
M_.mapping.epinf.eqidx = [31 ];
M_.mapping.ew.eqidx = [33 ];
M_.static_and_dynamic_models_differ = false;
M_.has_external_function = false;
M_.state_var = [8 9 14 15 16 25 26 27 29 30 31 32 33 34 35 36 37 38 39 40 ];
M_.exo_names_orig_ord = [1:7];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(41, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(7, 1);
M_.params = NaN(44, 1);
M_.endo_trends = struct('deflator', cell(41, 1), 'log_deflator', cell(41, 1), 'growth_factor', cell(41, 1), 'log_growth_factor', cell(41, 1));
M_.NNZDerivatives = [161; 0; -1; ];
M_.static_tmp_nbr = [17; 2; 0; 0; ];
M_.model_local_variables_static_tt_idxs = {
};
M_.params(12) = .025;
ctou = M_.params(12);
M_.params(23) = 1.5;
clandaw = M_.params(23);
M_.params(39) = 0.18;
cg = M_.params(39);
M_.params(3) = 10;
curvp = M_.params(3);
M_.params(1) = 10;
curvw = M_.params(1);
M_.params(42) = 0.5;
rho = M_.params(42);
M_.params(44) = 0.5;
alpha = M_.params(44);
lambda = 0.5;
M_.params(41) = 0.76;
rho_alpha = M_.params(41);
M_.params(40) = (-0.01);
alpha_int = M_.params(40);
M_.params(9) = .24;
calfa = M_.params(9);
cbeta=.9995;
M_.params(13) = 1.5;
csigma = M_.params(13);
M_.params(17) = 1.5;
cfc = M_.params(17);
M_.params(2) = 0.51;
cgy = M_.params(2);
M_.params(11) = 6.0144;
csadjcost = M_.params(11);
M_.params(14) = 0.6361;
chabb = M_.params(14);
M_.params(19) = 0.8087;
cprobw = M_.params(19);
M_.params(22) = 1.9423;
csigl = M_.params(22);
M_.params(21) = 0.6;
cprobp = M_.params(21);
M_.params(18) = 0.3243;
cindw = M_.params(18);
M_.params(20) = 0.47;
cindp = M_.params(20);
M_.params(10) = 0.2696;
czcap = M_.params(10);
M_.params(25) = 1.488;
crpi = M_.params(25);
M_.params(28) = 0.8762;
crr = M_.params(28);
M_.params(27) = 0.0593;
cry = M_.params(27);
M_.params(26) = 0.2347;
crdy = M_.params(26);
M_.params(29) = 0.9977;
crhoa = M_.params(29);
M_.params(31) = 0.5799;
crhob = M_.params(31);
M_.params(32) = 0.9957;
crhog = M_.params(32);
M_.params(33) = 0.9928;
crhols = M_.params(33);
M_.params(34) = 0.7165;
crhoqs = M_.params(34);
M_.params(30) = 1;
crhoas = M_.params(30);
M_.params(35) = 0;
crhoms = M_.params(35);
M_.params(36) = 0;
crhopinf = M_.params(36);
M_.params(37) = 0;
crhow = M_.params(37);
M_.params(8) = 0;
cmap = M_.params(8);
M_.params(7) = 0;
cmaw = M_.params(7);
M_.params(4) = 0;
constelab = M_.params(4);
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = (0.4618)^2;
M_.Sigma_e(2, 2) = (1.8513)^2;
M_.Sigma_e(3, 3) = (0.6090)^2;
M_.Sigma_e(4, 4) = (0.6017)^2;
M_.Sigma_e(5, 5) = (0.2397)^2;
M_.Sigma_e(6, 6) = (0.1455)^2;
M_.Sigma_e(7, 7) = (0.2089)^2;
estim_params_.var_exo = zeros(0, 10);
estim_params_.var_endo = zeros(0, 10);
estim_params_.corrx = zeros(0, 11);
estim_params_.corrn = zeros(0, 11);
estim_params_.param_vals = zeros(0, 10);
estim_params_.var_exo = [estim_params_.var_exo; 1, 0.4618, 0.01, 3, 4, 0.1, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 2, 0.1818513, 0.025, 5, 4, 0.1, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 3, 0.6090, 0.01, 3, 4, 0.1, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 4, 0.46017, 0.01, 3, 4, 0.1, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 5, 0.2397, 0.01, 3, 4, 0.1, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 6, 0.1455, 0.01, 3, 4, 0.1, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 7, 0.2089, 0.01, 3, 4, 0.1, 2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 29, .9676, .01, .9999, 1, 0.5, 0.20, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 31, .2703, .01, .9999, 1, 0.5, 0.20, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 32, .9930, .01, .9999, 1, 0.5, 0.20, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 34, .5724, .01, .9999, 1, 0.5, 0.20, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 35, .3, .01, .9999, 1, 0.5, 0.20, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 36, .8692, .01, .9999, 1, 0.5, 0.20, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 37, .9546, .001, .9999, 1, 0.5, 0.20, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 8, .7652, 0.01, .9999, 1, 0.5, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 7, .8936, 0.01, .9999, 1, 0.5, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 11, 6.3325, 2, 15, 3, 4, 1.5, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 13, 1.2312, 0.25, 3, 3, 1.50, 0.375, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 14, 0.7205, 0.001, 0.99, 1, 0.7, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 19, 0.7937, 0.3, 0.95, 1, 0.5, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 22, 2.8401, 0.25, 10, 3, 2, 0.75, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 21, 0.7813, 0.5, 0.95, 1, 0.5, 0.10, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 18, 0.4425, 0.01, 0.99, 1, 0.5, 0.15, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 20, 0.3291, 0.01, 0.99, 1, 0.5, 0.15, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 10, 0.2648, 0.01, 1, 1, 0.5, 0.15, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 17, 1.4672, 1.0, 3, 3, 1.25, 0.125, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 25, 1.7985, 1.0, 3, 3, 1.5, 0.25, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 28, 0.8258, 0.5, 0.975, 1, 0.75, 0.10, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 27, 0.0893, 0.001, 0.5, 3, 0.125, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 26, 0.2239, 0.001, 0.5, 3, 0.125, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 5, 0.7, 0.1, 2.0, 2, 0.625, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 6, 0.7420, 0.01, 2.0, 2, 0.25, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 4, 1.2918, (-10.0), 10.0, 3, 0.0, 2.0, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 38, 0.3982, 0.1, 0.8, 3, 0.4, 0.10, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 2, 0.05, 0.01, 2.0, 3, 0.5, 0.25, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 9, 0.24, 0.01, 1.0, 3, 0.3, 0.05, NaN, NaN, NaN ];
options_.lik_init = 2;
options_.mh_drop = 0.2;
options_.mh_jscale = 0.20;
options_.mh_nblck = 2;
options_.mh_replic = 0;
options_.mode_compute = 0;
options_.prefilter = 0;
options_.presample = 4;
options_.datafile = 'usmodel_data';
options_.mode_file = 'usmodel_mode';
options_.optim_opt = '''MaxIter'',200';
options_.first_obs = 71;
options_.order = 1;
var_list_ = {};
oo_recursive_=dynare_estimation(var_list_);
options_.irf = 20;
options_.order = 2;
options_.irf_shocks = {'ea'};
var_list_ = {'dy'};
[info, oo_, options_, M_] = stoch_simul(M_, options_, oo_, var_list_);


oo_.time = toc(tic0);
disp(['Total computing time : ' dynsec2hms(oo_.time) ]);
if ~exist([M_.dname filesep 'Output'],'dir')
    mkdir(M_.dname,'Output');
end
save([M_.dname filesep 'Output' filesep 'SW_results.mat'], 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'SW_results.mat'], 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'SW_results.mat'], 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'SW_results.mat'], 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'SW_results.mat'], 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'SW_results.mat'], 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'SW_results.mat'], 'oo_recursive_', '-append');
end
disp('Note: 34 warning(s) encountered in the preprocessor')
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
